### ISSUE TITLE
No time display or top bar while on cooldown

### ISSUE THREAD

**Issue by conyerbd** [Lleafll/doom-shards#4]
Might be an addon conflict with bartender but I'm not sure if this is happening elsewhere.

**Comment by Lleafll** [comment]
Can you please elaborate?

What I'm getting is:
You're successfully casting Doom on a target.
Expected behavior: Doom tick prediction bar and text appear.
Observed behavior: Bar and text don't appear.

Is that correct?

You're suspecting a conflict with Bartender; have you tried Doom Shards without Bartender?

**Comment by Lleafll** [comment]
Closed because of lacking details.
